// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy-aLSX4RPNx1Ap5-LxKODXRk5kdbvJn8',
    appId: '1:550945986005:web:1c120f8cecb73b9bcd195c',
    messagingSenderId: '550945986005',
    projectId: 'indelible-ds',
    authDomain: 'indelible-ds.firebaseapp.com',
    storageBucket: 'indelible-ds.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4oXdn06nx1QcqcAPGggnX44mhl9F3hE8',
    appId: '1:550945986005:android:546af47c8b49f7f0cd195c',
    messagingSenderId: '550945986005',
    projectId: 'indelible-ds',
    storageBucket: 'indelible-ds.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDErIrD3hRlDFVIIZqKehWR_INAxcNEHEo',
    appId: '1:550945986005:ios:bdef6b6de9fe8073cd195c',
    messagingSenderId: '550945986005',
    projectId: 'indelible-ds',
    storageBucket: 'indelible-ds.firebasestorage.app',
    iosBundleId: 'com.example.indelible',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDErIrD3hRlDFVIIZqKehWR_INAxcNEHEo',
    appId: '1:550945986005:ios:bdef6b6de9fe8073cd195c',
    messagingSenderId: '550945986005',
    projectId: 'indelible-ds',
    storageBucket: 'indelible-ds.firebasestorage.app',
    iosBundleId: 'com.example.indelible',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy-aLSX4RPNx1Ap5-LxKODXRk5kdbvJn8',
    appId: '1:550945986005:web:2339ace653e42772cd195c',
    messagingSenderId: '550945986005',
    projectId: 'indelible-ds',
    authDomain: 'indelible-ds.firebaseapp.com',
    storageBucket: 'indelible-ds.firebasestorage.app',
  );
}
